# Generated by Django 2.2 on 2020-08-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=45)),
                ('unit_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=45)),
                ('meal_note', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_meals', to='userapp.User')),
                ('mealcost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_need', to='meal.MealType')),
                ('ordered_by', models.ManyToManyField(related_name='orders', to='userapp.User')),
            ],
        ),
    ]
