# Generated by Django 2.2 on 2020-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='offered_portion',
            field=models.IntegerField(default=4),
        ),
    ]
